/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tianyang Feng
 */

package optionpricer;

import option.putOption;
import option.callOption;
import option.Option;
import algorithm.model.Algorithm;
import java.lang.*;
import java.util.*;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class OptionPricerUI extends javax.swing.JFrame {    
    /**
     * Creates new form user
     */
    private double s0;
    private double sK;
    private double t;
    private double rFR;
    private double v;
    
    private int option;
    private String type;
    private String algo;    
    private Option myOption;
    private AlgoFactory myAlgoFactory;
    private Algorithm myAlgo;
    private Calculation myCalculation; 
    private Graph myGraph;
    
    public OptionPricerUI() {
        initComponents();
        myAlgoFactory = new AlgoFactory();
        System.out.println(algo);
        AlgorithmBusiness.initAlgorithms();
        updateAlgorithmCombobox();
        this.AlgorithmComboBox.addItem("Bionomial Tree");
        this.AlgorithmComboBox.addItem("Simulation");
        algo = this.AlgorithmComboBox.getSelectedItem().toString();
    }

     public String getJarFilePath() {
        return jarFilePathTextField.getText().trim();
    }

    public void setJarFilePath(String JarFilePath) {
        this.jarFilePathTextField.setText(JarFilePath);
    }

    public JComboBox getAlgorithmCombo() {
        return AlgorithmComboBox;
    }

    public void setAlgorithmCombo(JComboBox algorithm) {
        this.AlgorithmComboBox = algorithm;
    }

    public JTextField getOptionPrice() {
        return OptionPriceTextField;
    }

    public void setOptionPrice(String optionPrice) {
        this.OptionPriceTextField.setText(optionPrice);
    }

    public Option getMyOption() {
        return myOption;
    }

    public void setMyOption(Option op) {
        myOption = op;
    }

    public String getSelectedAlgorithmName(){
        return ((String)AlgorithmComboBox.getSelectedItem()).trim();
    }
    
    public void updateAlgorithmCombobox() {
        Map<String,Algorithm> algorithms = AlgorithmBusiness.getCurrentAlgorithm();
        AlgorithmComboBox.removeAllItems();
        Set<String> keys = algorithms.keySet();
        for (String key : keys) {
            AlgorithmComboBox.addItem(key);
        }
        if (AlgorithmComboBox.getItemCount() > 0) AlgorithmComboBox.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionButtonGroup = new javax.swing.ButtonGroup();
        TypeButtonGroup = new javax.swing.ButtonGroup();
        canvas1 = new java.awt.Canvas();
        CalculationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AmericanRadioButton = new javax.swing.JRadioButton();
        EuroRadioButton = new javax.swing.JRadioButton();
        AsianRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        PutRadioButton = new javax.swing.JRadioButton();
        CallRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        StrikePriceTextField = new javax.swing.JTextField();
        UnderlyingPriceTextField = new javax.swing.JTextField();
        TermTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        VolatilityTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RiskFreeRateTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CalculateButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AlgorithmComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        OptionPriceTextField = new javax.swing.JTextField();
        uploadButton = new javax.swing.JButton();
        ViewGraphButton = new javax.swing.JButton();
        jarFilePathTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Option Pricer");
        setName("Option Pricer"); // NOI18N

        CalculationPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("The Option Pricer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Option:");

        OptionButtonGroup.add(AmericanRadioButton);
        AmericanRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AmericanRadioButton.setText("American");
        AmericanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmericanRadioButtonActionPerformed(evt);
            }
        });

        OptionButtonGroup.add(EuroRadioButton);
        EuroRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EuroRadioButton.setText("European");
        EuroRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EuroRadioButtonActionPerformed(evt);
            }
        });

        OptionButtonGroup.add(AsianRadioButton);
        AsianRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AsianRadioButton.setText("Asian");
        AsianRadioButton.setActionCommand("Asia");
        AsianRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsianRadioButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Type:");

        TypeButtonGroup.add(PutRadioButton);
        PutRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PutRadioButton.setText("Put");
        PutRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PutRadioButtonActionPerformed(evt);
            }
        });

        TypeButtonGroup.add(CallRadioButton);
        CallRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CallRadioButton.setText("Call");
        CallRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Strike Price:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Volatility:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Risk Free interest:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Maturity Time (in year):");

        CalculateButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Underlying Price:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Algorithm:");

        AlgorithmComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AlgorithmComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgorithmComboBoxActionPerformed(evt);
            }
        });
        AlgorithmComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AlgorithmComboBoxFocusGained(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Option Price:");

        OptionPriceTextField.setEditable(false);

        uploadButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        ViewGraphButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ViewGraphButton.setText("View Graph");
        ViewGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewGraphButtonActionPerformed(evt);
            }
        });

        jarFilePathTextField.setEditable(false);

        browseButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Add New Algorithm:");

        javax.swing.GroupLayout CalculationPanelLayout = new javax.swing.GroupLayout(CalculationPanel);
        CalculationPanel.setLayout(CalculationPanelLayout);
        CalculationPanelLayout.setHorizontalGroup(
            CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculationPanelLayout.createSequentialGroup()
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculationPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(CalculationPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ViewGraphButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculationPanelLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(AlgorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(CalculationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculationPanelLayout.createSequentialGroup()
                        .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AmericanRadioButton)
                            .addComponent(PutRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalculationPanelLayout.createSequentialGroup()
                                .addComponent(EuroRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AsianRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CallRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(CalculationPanelLayout.createSequentialGroup()
                        .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jarFilePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(20, 20, 20)
                        .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(browseButton)
                            .addComponent(uploadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CalculationPanelLayout.createSequentialGroup()
                        .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalculationPanelLayout.createSequentialGroup()
                                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(15, 15, 15)
                                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(VolatilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RiskFreeRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UnderlyingPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StrikePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CalculationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(82, 82, 82)
                                .addComponent(OptionPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        CalculationPanelLayout.setVerticalGroup(
            CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AmericanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EuroRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AsianRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PutRadioButton)
                    .addComponent(CallRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(StrikePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnderlyingPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolatilityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(RiskFreeRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AlgorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseButton)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jarFilePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadButton))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(OptionPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculationPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculationPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ViewGraphButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        uploadButton.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CalculationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CalculationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EuroRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EuroRadioButtonActionPerformed
        option = Option.EUROPEAN;     
        System.out.println(option);
    }//GEN-LAST:event_EuroRadioButtonActionPerformed

    private void AsianRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsianRadioButtonActionPerformed
        option = Option.ASIAN;
        System.out.println(option);
    }//GEN-LAST:event_AsianRadioButtonActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
            myOption = this.newOption();
            algo = this.AlgorithmComboBox.getSelectedItem().toString();
            if (algo == "Bionomial Tree" || algo =="Simulation"){
              myAlgo = this.newAlgo();   
            }
            else{
                DropInAlgorithm dropIn = new DropInAlgorithm();
                myAlgo = dropIn.calculate(this);
            }             
            
            myCalculation = new Calculation();
            this.OptionPriceTextField.setText("" + myCalculation.calculatePrice(myOption, myAlgo));
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void PutRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PutRadioButtonActionPerformed
        // TODO add your handling code here:
        type = "Put";
    }//GEN-LAST:event_PutRadioButtonActionPerformed

    private void CallRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallRadioButtonActionPerformed
        // TODO add your handling code here:
        type = "Call";
    }//GEN-LAST:event_CallRadioButtonActionPerformed

    private void AmericanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmericanRadioButtonActionPerformed
        // TODO add your handling code here:
        option = Option.AMERICAN;     
        System.out.println(option);
    }//GEN-LAST:event_AmericanRadioButtonActionPerformed

    private void ViewGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewGraphButtonActionPerformed
        // TODO add your handling code here:
        myOption = this.newOption();
        if (algo == "Bionomial Tree" || algo =="Simulation"){
              myAlgo = this.newAlgo();   
            }
            else{
                DropInAlgorithm dropIn = new DropInAlgorithm();
                myAlgo = dropIn.calculate(this);
            }    
        myGraph = new Graph();
        myGraph.calculateGraph(myOption,myAlgo);
        JFrame f = new JFrame();       
        f.add(myGraph);
        f.setSize(400,400);
        f.setLocation(300,300);
        f.setTitle("Volatility Smile");
        f.setVisible(true);  
    }//GEN-LAST:event_ViewGraphButtonActionPerformed

    private void AlgorithmComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AlgorithmComboBoxFocusGained
        // TODO add your handling code here:
        if (option == Option.ASIAN){      
         this.AlgorithmComboBox.removeItem("Bionomial Tree");
         boolean allAlgo = false;
            for(int i= 0; i<this.AlgorithmComboBox.getItemCount(); i++){
                System.out.println(i);
                if(this.AlgorithmComboBox.getItemAt(i) == "Simulation"){
                    allAlgo = true;
                }
            }
            if (allAlgo == false){
                this.AlgorithmComboBox.addItem("Simulation");
            }}
        else{
            boolean allAlgo = false;
            for(int i= 0; i<this.AlgorithmComboBox.getItemCount(); i++){
                System.out.println(i);
                if(this.AlgorithmComboBox.getItemAt(i) == "Bionomial Tree"){
                    allAlgo = true;
                }
            }
            if (allAlgo == false){
                this.AlgorithmComboBox.addItem("Bionomial Tree");
            }
        }
    }//GEN-LAST:event_AlgorithmComboBoxFocusGained

    private void AlgorithmComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgorithmComboBoxActionPerformed
        // TODO add your handling code here:
//        algo = this.AlgorithmComboBox.getSelectedItem().toString();
//        System.out.println(algo);
    }//GEN-LAST:event_AlgorithmComboBoxActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        AlgorithmBusiness business = new AlgorithmBusiness();
        business.loadAlgorithms(this);
        updateAlgorithmCombobox();
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        AlgorithmBusiness business = new AlgorithmBusiness();
        business.getJarFilePath(this);
    }//GEN-LAST:event_browseButtonActionPerformed

    private Option newOption(){
       try{
            s0 =Double.parseDouble(this.UnderlyingPriceTextField.getText());
            sK = Double.parseDouble(this.StrikePriceTextField.getText());
            t = Double.parseDouble(this.TermTextField.getText());
            rFR = Double.parseDouble(this.RiskFreeRateTextField.getText());
            v = Double.parseDouble(this.VolatilityTextField.getText());
             }catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Please input all parameters","Warning",JOptionPane.ERROR_MESSAGE);
            }        
       if (type == "Put") {
                return new putOption(s0, sK, t, rFR, v, option);
            } else{
                return new callOption(s0, sK, t, rFR, v, option);
            }       
    }
    
    private Algorithm newAlgo(){
         return myAlgoFactory.createAlgorithm(algo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionPricerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionPricerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionPricerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionPricerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionPricerUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AlgorithmComboBox;
    private javax.swing.JRadioButton AmericanRadioButton;
    private javax.swing.JRadioButton AsianRadioButton;
    private javax.swing.JButton CalculateButton;
    private javax.swing.JPanel CalculationPanel;
    private javax.swing.JRadioButton CallRadioButton;
    private javax.swing.JRadioButton EuroRadioButton;
    private javax.swing.ButtonGroup OptionButtonGroup;
    private javax.swing.JTextField OptionPriceTextField;
    private javax.swing.JRadioButton PutRadioButton;
    private javax.swing.JTextField RiskFreeRateTextField;
    private javax.swing.JTextField StrikePriceTextField;
    private javax.swing.JTextField TermTextField;
    private javax.swing.ButtonGroup TypeButtonGroup;
    private javax.swing.JTextField UnderlyingPriceTextField;
    private javax.swing.JButton ViewGraphButton;
    private javax.swing.JTextField VolatilityTextField;
    private javax.swing.JButton browseButton;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jarFilePathTextField;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
